/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Location } from './location';


export interface Expert { 
    address?: Address;
    createdAt?: Date;
    deletedAt?: Date;
    distanceMeter?: number;
    id?: string;
    likes?: number;
    location?: Location;
    name?: string;
    phone?: string;
    profession?: Array<string>;
}
