/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';
import { Location } from './location';
import { Provider } from './provider';


export interface User { 
    accessToken?: string;
    address?: Address;
    createdAt?: Date;
    deletedAt?: Date;
    email?: string;
    emailVerified?: boolean;
    experts?: Array<string>;
    expiresAt?: Date;
    followedBy?: Array<string>;
    followers?: Array<string>;
    id?: string;
    imageUrl?: string;
    language?: string;
    locationByAddress?: Location;
    name?: string;
    password?: string;
    provider?: User.ProviderEnum;
    providerId?: string;
    providers?: Provider;
    updatedAt?: Date;
}
export namespace User {
    export type ProviderEnum = 'local' | 'facebook' | 'google' | 'github';
    export const ProviderEnum = {
        Local: 'local' as ProviderEnum,
        Facebook: 'facebook' as ProviderEnum,
        Google: 'google' as ProviderEnum,
        Github: 'github' as ProviderEnum
    };
}
