matrix:
  include:
    - language: java
      sudo: false
      jdk: openjdk11
      services:
      - docker
      before_script:
      - "cd ./server"
      - docker-compose up -d
      - sleep 15
      script:
      - "./mvnw clean test"
    - language: node_js
      node_js: "8.15"
      script:
      - "cd ./client"
      - "npm install -g @angular/cli && npm install"
      - "ng build --aot"

