matrix:
  include:
    - language: java
      jdk: openjdk11
      services:
      - elasticsearch
      before_script:
      - "elasticsearch -v"
      - "sleep 10"
      script:
      - "cd ./server"
      - "./mvnw clean test"
    - language: node_js
      node_js: "8.15"
      script:
      - "cd ./client"
      - "npm install -g @angular/cli && npm install"
      - "ng build --aot"

